name: "test status"
on:
  - "push"
jobs:
  test:
    runs-on: "ubuntu-18.04"
    strategy:
      matrix:
        include:
          - vim_type: "Vim"
            vim_version: "v8.2.4318"
            lua_version: "luajit-2.1.0-beta3"
          # - vim_type: "Neovim"
          #   vim_version: "stable"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 5
      - name: "install lua"
        uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "${{ matrix.lua_version }}"
      - name: "install ${{ matrix.vim_type }}"
        uses: "thinca/action-setup-vim@v1"
        with:
          vim_version: "${{ matrix.vim_version }}"
          vim_type: "${{ matrix.vim_type }}"
      - name: "run tests"
        run: ./t/run.sh
